# Generated by Django 6.0.1 on 2026-02-25 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ad_placement', models.CharField(choices=[('homepage', 'homepage'), ('sidebar', 'sidebar')], max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'advertisement',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('reader', 'reader'), ('jounralist', 'jounralist'), ('advertiser', 'advertiser')], max_length=20)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('profile_image', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AdMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.TextField(max_length=255)),
                ('media_type', models.CharField(max_length=50)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.advertisement')),
            ],
            options={
                'db_table': 'ad_media',
            },
        ),
        migrations.CreateModel(
            name='News_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=20)),
                ('is_breaking', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.category')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.city')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.state')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.users')),
            ],
            options={
                'db_table': 'news_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_content', models.TextField()),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.news_article')),
            ],
            options={
                'db_table': 'article_translation',
            },
        ),
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=50)),
                ('file_url', models.TextField(max_length=255)),
                ('file_size', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.news_article')),
            ],
            options={
                'db_table': 'article_media',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.state'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(choices=[('free', 'free'), ('premium', 'premium')], max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.users')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.news_article')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.users')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('report_status', models.CharField(choices=[('pending', 'pending'), ('reviewed', 'reviewed'), ('dismissed', 'dismissed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.city')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.state')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.users')),
            ],
            options={
                'db_table': 'citizen_report',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertiser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.users'),
        ),
    ]
