# Generated by Django 6.0.1 on 2026-02-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_product_productcolor_product_productstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseCode', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
